298 feature skip waypoints automatically
Azeroth-Pilot-Reloaded/azeroth-pilot-reloaded pull request #299
Opened 2024-06-05 14:08 UTC by Kamian404

implements the auto skip waypoints + when you can fly

2024-06-05 16:05 UTC, Neogeekmo requested changes

2024-06-05 16:05 UTC, Neogeekmo commented on APR-Core/Config.lua
> +                        width = "full",
same

2024-06-05 16:05 UTC, Neogeekmo commented on APR-Core/Config.lua
> +                        width = "full",
maybe use `optionsWidthAutomation` to put them next to each other?

2024-06-05 16:05 UTC, Neogeekmo commented on APR-Core/Config.lua
> +                        set = SetProfileOption,
as it's not logical to have both enabled, you'd have to switch the state of the other when you enable one of them
```lua
set = function(info, value)
    SetProfileOption(info, value)
    if (value) then self.profile.autoSkipWaypointsFly = false end
 end
 ```

2024-06-05 16:05 UTC, Neogeekmo commented on APR-Core/Config.lua
> +                        set = SetProfileOption,
as it's not logical to have both enabled, you'd have to switch the state of the other when you enable one of them
```lua
set = function(info, value)
    SetProfileOption(info, value)
    if (value) then self.profile.autoSkipAllWaypoints= false end
 end
 ```

2024-06-05 16:05 UTC, Neogeekmo commented on APR-Core/Config.lua
you forgot to add 
- autoSkipAllWaypoints
- autoSkipWaypointsFly

in the profile in APR.settings:InitializeSettings()

2024-06-05 16:05 UTC, Neogeekmo commented on APR-Core/helpers/Utils.lua
> +    if (IsSpellKnown(34090) or IsSpellKnown(34091) or IsSpellKnown(90265)) then
yes, it's better to use IsSpellKnown :)

2024-06-05 16:07 UTC, Neogeekmo commented on APR-Core/Config.lua
both equal false by default

2024-06-05 16:08 UTC, Neogeekmo commented
If you want you can also write the changelog of v3.3.1 with this fix to deploy it right after the merge

2024-06-06 08:08 UTC, Kamian404 commented on APR-Core/Config.lua
> +                        width = "full",
needed to set the width by myself since 1.75 is too width for the container

2024-06-06 09:19 UTC, Kamian404 commented on APR-Core/helpers/Utils.lua
> +    if (IsSpellKnown(34090) or IsSpellKnown(34091) or IsSpellKnown(90265)) then
👍

2024-06-06 09:19 UTC, Kamian404 commented on APR-Core/Config.lua
👍

2024-06-06 10:04 UTC, Neogeekmo approved these changes

2024-06-06 10:49 UTC, merged